<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sqlqs.Sidecar.Sql</RootNamespace>
    <AssemblyName>Sqlqs.Sidecar.Sql</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sqlqs.Sidecar.Contracts\Sqlqs.Sidecar.Contracts.csproj" />
  </ItemGroup>

</Project>
